version: '3.2'

services:
  app:
    image: minsungkim/myapp
    build: .
    env_file:
      - .env.staging
    ports:
      - 8000:8000
    depends_on:
      - db
    container_name: myapp

  db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    container_name: mydb
